language: java
install: true

deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: 
    secure: "Q6wNLf4lN7DzO4zz4WFRbEVxigHtwNPDZ1bpkgMlnIOIpDC/b3Wk3Tj1kRx8+8SuQRH7qO0N291oTD3+hOPlu18YwJaMNXcrYHEjTciucOmz4mhmoVDzJweR6+syUDPe+4bCwk3ePBlIsveHZDxpRpaBP8v9AayFkcb69Zb50DGG1i9c99E6xpQn62r/D7LCVjAgCJmYU+BshSGt0AdLLaiO1IN0TmCx26gHnGsvYZdCtFHLhjlyelNNOL4V2bw0/ZY6QIH4SIKZoRdLnXrSRce8BltMdC8OmycHMny4WKH3bBWKN+Qytzc5ohswt24j8ceBo1qZrFsue9YLVzBLzuxFKfiDogqODiWc2Ppqbrz4cMbKOo4fiqez8gmm17l4xIU4dq0Jh+JAhQG3hWGDIek9bKQiYkEyTWIoh2A0Jx5sRIxcpoiMt11laOQgoKR8zElV66Hf9cKN27AfFvu8Q5/LAncFRogbg8cKj70SMeMsEjL9lvUYTm4vcyF4oiBGCMdhb39JGSMfq0PW682jLoCnReUpH8jilYNTbNrzDY2WmEaXA6PHks4HB13nWSJEWTsapghEBQzVFkkOvPuyBl2HZ9bFp1uHttC3eKSMojA9/1onSLqM98c4Mw6gIfXp+ak2S75JQpfk23XtJObp6jc2AunGc6PNN4v8b24O+cA="
  secret_access_key:
    secure: "BRSSOlXNscHQn/Nzs+fYJPjYO+zokl+okMQ16l/ey0KixAp3De/FIWIBBZ3OJ3R9sj82kfBY5NH+GNIFVNB5nvbYbUjsxWJBa1WpKwgz4OSPrhGPiy4YhV7FnRjT8Mmq5dHJeawTLnWxrhnPAxCCblyLOGDRIWVfqTs4m+FlDLHLYgAZ3t8wVUDGhawhTVTcG492per1Mmnm30cMJT8caJM1K/EaE3d++7tntyq73iY3xuYUpuJlXB3PD9Kd/xy4MGgFZq4V/wCiWIgvrMHXgAtg5IJDi20jVZSiWGtFutxGRaIpbiVjXn9/4km+u30x3SwrREh0OuRsfQ1QTQFbEZP+JALLZMq22MM6aRITzUP1SpiHuneOUqubGUqY8FPLFoPUZ705yLhlfg7LjB9Zuy7NT5lHJr55hCsz2GJlmwxlIWJvnHqwNmb19qE15RjFEWFfKsRuADwZn1auD4mpDloVYDq80TifWQRt/8QequFG94lQtca08GteF/palYb+k+AeVkrlNTP9pL2B2q+o2IBDOcj/9bB4NHypRr7O4YlLY9Jc1qDkWd/umx4P7GVKTtwKof/7IiOMw4+PwiJDf0h7OP3kXeQuXEqRvNSRNBX/WCIWhvat1DaopGETtGg7OkZc0mP4KgO7/I+rdh0dKNUGCgHF+/jVZBMRxE+5ut8="
  application: "geoscience-portal-codedeploy"
  deployment_group: "geoscience-portal-group"
  region: "ap-southeast-2"

cache: 
  directories:
    - $HOME/.m2
  branches:
    only:
      - master
  jdk:
    - oraclejdk8
