language: java
install: true
before_deploy:
  - travis/build.sh
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: 
    secure: "Q6wNLf4lN7DzO4zz4WFRbEVxigHtwNPDZ1bpkgMlnIOIpDC/b3Wk3Tj1kRx8+8SuQRH7qO0N291oTD3+hOPlu18YwJaMNXcrYHEjTciucOmz4mhmoVDzJweR6+syUDPe+4bCwk3ePBlIsveHZDxpRpaBP8v9AayFkcb69Zb50DGG1i9c99E6xpQn62r/D7LCVjAgCJmYU+BshSGt0AdLLaiO1IN0TmCx26gHnGsvYZdCtFHLhjlyelNNOL4V2bw0/ZY6QIH4SIKZoRdLnXrSRce8BltMdC8OmycHMny4WKH3bBWKN+Qytzc5ohswt24j8ceBo1qZrFsue9YLVzBLzuxFKfiDogqODiWc2Ppqbrz4cMbKOo4fiqez8gmm17l4xIU4dq0Jh+JAhQG3hWGDIek9bKQiYkEyTWIoh2A0Jx5sRIxcpoiMt11laOQgoKR8zElV66Hf9cKN27AfFvu8Q5/LAncFRogbg8cKj70SMeMsEjL9lvUYTm4vcyF4oiBGCMdhb39JGSMfq0PW682jLoCnReUpH8jilYNTbNrzDY2WmEaXA6PHks4HB13nWSJEWTsapghEBQzVFkkOvPuyBl2HZ9bFp1uHttC3eKSMojA9/1onSLqM98c4Mw6gIfXp+ak2S75JQpfk23XtJObp6jc2AunGc6PNN4v8b24O+cA="
  secret_access_key:
    secure: "BRSSOlXNscHQn/Nzs+fYJPjYO+zokl+okMQ16l/ey0KixAp3De/FIWIBBZ3OJ3R9sj82kfBY5NH+GNIFVNB5nvbYbUjsxWJBa1WpKwgz4OSPrhGPiy4YhV7FnRjT8Mmq5dHJeawTLnWxrhnPAxCCblyLOGDRIWVfqTs4m+FlDLHLYgAZ3t8wVUDGhawhTVTcG492per1Mmnm30cMJT8caJM1K/EaE3d++7tntyq73iY3xuYUpuJlXB3PD9Kd/xy4MGgFZq4V/wCiWIgvrMHXgAtg5IJDi20jVZSiWGtFutxGRaIpbiVjXn9/4km+u30x3SwrREh0OuRsfQ1QTQFbEZP+JALLZMq22MM6aRITzUP1SpiHuneOUqubGUqY8FPLFoPUZ705yLhlfg7LjB9Zuy7NT5lHJr55hCsz2GJlmwxlIWJvnHqwNmb19qE15RjFEWFfKsRuADwZn1auD4mpDloVYDq80TifWQRt/8QequFG94lQtca08GteF/palYb+k+AeVkrlNTP9pL2B2q+o2IBDOcj/9bB4NHypRr7O4YlLY9Jc1qDkWd/umx4P7GVKTtwKof/7IiOMw4+PwiJDf0h7OP3kXeQuXEqRvNSRNBX/WCIWhvat1DaopGETtGg7OkZc0mP4KgO7/I+rdh0dKNUGCgHF+/jVZBMRxE+5ut8="
  application: "geonetwork-codedeploy"
  deployment_group: "geonetwork-group"
  region: "ap-southeast-2"
env:
  global:
    - secure: "Z0eV8OBkbhz/QJdxml8HWeN0gg2H4tHPgocJ3Xgr1n6C8ez8VnJrEd23jYu1pjrzESSvVg9lCzHSsIBsjokEDZ6JFdjM15arnHBUez03l5unoOW6nTn6pctUopgT4Do46OyAOAqtAJFyBURRnaDtTTGyAoTrl/apSOceVE1VvGnzDApvi4b6MQZrkpADCeBsXBlXivSyMlEwc0psLltnS1QjoJuOyPLtkQcYaBw3G4F5VpMnmRcEfZgAD+0Y7JXOQVKKHuK65uKc3BCvsuRYcbK309PVHFa1mj05nGt53cDiOxgG0kFbFBBpl/Io8EJQzvxwybNMLq2q6TuPFEq3ybMVzPPWMmaWD1m6sA+E3RdGeRznLyAVkKSOdUmW9/Rk33HU7Fq+jnevD1LcovX+oZ/bJiVyoQAF5wnjn1Al/4QzwRSOSDlrVMqWIzpVH48epPeIr2vUhogOi3B2YSuNoLFc6wLXWYdUpcCatlgtFbUlSPr8/zOKfUj3eDPDqSN9rCebvnsuc5gAYwZSjIr9PQJGtKPHuhFh4ebpY3P3ZRabsOlZE16GGoK2erkBYJ6wl0LKXshpl/ofyzBtJSPfh9zAZ+DYD8tJZrF8X5RK5aCPjAI1/NDkZv5HxkYIQw2jw05f/yZGcoAr6SwP+DzVsC0KtPF48Ykb8T3Tr/TtJHA="
    - secure: "RyB44A6WT6YKezJnD0k/vEzbtP7prMqQNTxdEIT2snN+YEl9/FSBLTCGRf0Xj+vpVTUXvgtvWXhvlhIKohZ/0yz91QROECHEMZykbiJUEo5b0+KJF0OJdacbWjgpz1nPTxF3hlFd3GBf85kGYhoc52Zeaw4+NY2qKs583gx/Yuq/Yb+71WNqWWZAXDTlcmLoR5z1IlIgcyKaGVql9pR215z1qFaAinLYUlSlnKY0qHv0vbyIywtX6YAcAjjuLlAXwy8hVI7UCYnrhTeI9JM+rzaaCx7bVAcmfu9gpI1GyPXAX2CBp4/HKTl6O68QJUg4MCTMlVJiv8j7wBY+VehwT/1edBZWOdL+usKCQbGOlmtIB6ljY+VhtHlG0miH3bVsDOV8y6wecGq5iSwsttTwA7YP3ghiNmu+Yo6VEHAJONT6VYkR1+3bD3rgG9Bx/EER6SIo4Xsdn4qQVM0iWzKNkNpZAKWEiJ9FX2x1XpNqM2cL6Dpsqt+Mf2aUk/4gNwwZjRwugubnwpC41Rl8Hqwo4IBwWiKS+5ETZ8pLxHYC+FrKY8c4oa4bY+lisqlYWFn1u2S7PcLszXIO7sDbvDJfBA9gVm6ixHSKHDEToFvO2dF1xJI7fz+cSfmHPTnR2Yjyms1TQ1nY42CfCcUgCJfY7F6vqKxMDLSeHPxaxPDbTfA="
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
jdk:
  - oraclejdk8
