version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/geonetwork
hooks:
  BeforeInstall:
    - location: scripts/create_directory.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/load_postgres.sh
      timeout: 300
      runas: root
